[package]
name = "ufo2nft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
norad = "0.6.0"
quick-xml = "0.22.0"
failure = "0.1.6"
